"""
GENERATED CODE - DO NOT EDIT
Source: survey-types.jsonld
Generated by: codegen.py
"""

from typing import Literal

# XLSForm type → standardized type
TYPE_MAP: dict[str, str] = {
    "integer": "integer",
    "int": "integer",
    "decimal": "decimal",
    "text": "text",
    "string": "text",
    "note": "note",
    "date": "date",
    "time": "time",
    "datetime": "datetime",
    "select_one": "select_one",
    "select_multiple": "select_multiple",
    "rank": "rank",
    "calculate": "calculate",
    "geopoint": "geopoint",
    "geotrace": "geotrace",
    "geoshape": "geoshape",
    "start-geopoint": "start-geopoint",
    "image": "image",
    "audio": "audio",
    "video": "video",
    "file": "file",
    "background-audio": "background-audio",
    "barcode": "barcode",
    "phonenumber": "phonenumber",
    "email": "email",
    "csv-external": "csv-external",
    "range": "range",
    "acknowledge": "acknowledge",
    "select_one_from_file": "select_one_from_file",
    "select_multiple_from_file": "select_multiple_from_file",
}

# XLSForm metadata types (silently skipped during conversion)
METADATA_TYPES: set[str] = {
    "start",
    "end",
    "today",
    "deviceid",
    "username",
    "hidden",
    "audit",
}

# XLSForm types that are recognized but unsupported in LimeSurvey TSV pipeline
UNSUPPORTED_TYPES: set[str] = {
    "geopoint",
    "geotrace",
    "geoshape",
    "start-geopoint",
    "image",
    "audio",
    "video",
    "file",
    "background-audio",
    "barcode",
    "phonenumber",
    "email",
    "csv-external",
    "range",
    "acknowledge",
    "select_one_from_file",
    "select_multiple_from_file",
}

# Structural types (begin_group, end_group, begin_repeat, end_repeat)
STRUCTURAL_TYPES: set[str] = {
    "begin_group",
    "begin_repeat",
    "end_group",
    "end_repeat",
}

# Standardized type → (intrvl, format_type). Filter: DDI-emittable (has ddi.intrvl).
DDI_TYPE_MAP: dict[str, tuple[str, str]] = {
    "integer": ("contin", "numeric"),
    "decimal": ("contin", "numeric"),
    "text": ("discrete", "character"),
    "note": ("discrete", "character"),
    "date": ("discrete", "character"),
    "time": ("discrete", "character"),
    "datetime": ("discrete", "character"),
    "select_one": ("discrete", "numeric"),
    "select_multiple": ("discrete", "numeric"),
    "rank": ("discrete", "numeric"),
    "calculate": ("discrete", "character"),
    "range": ("contin", "numeric"),
    "acknowledge": ("discrete", "numeric"),
    "select_one_from_file": ("discrete", "numeric"),
    "select_multiple_from_file": ("discrete", "numeric"),
    "hidden": ("discrete", "character"),
}

# Standardized type → responseDomainType for <qstn>
RESPONSE_DOMAIN_MAP: dict[str, str] = {
    "integer": "numeric",
    "decimal": "numeric",
    "text": "text",
    "note": "text",
    "date": "text",
    "time": "text",
    "datetime": "text",
    "select_one": "category",
    "select_multiple": "multiple",
    "rank": "category",
    "calculate": "text",
    "range": "numeric",
    "acknowledge": "text",
    "select_one_from_file": "category",
    "select_multiple_from_file": "multiple",
    "hidden": "text",
}

# Standardized type → measurement level
MEASURE_MAP: dict[str, str] = {
    "integer": "ratio",
    "decimal": "ratio",
    "date": "interval",
    "time": "interval",
    "datetime": "interval",
    "select_one": "nominal",
    "select_multiple": "nominal",
    "rank": "ordinal",
    "range": "ratio",
    "select_one_from_file": "nominal",
    "select_multiple_from_file": "nominal",
}
