"""Integration-test fixtures: boot qwacback + schematron-worker via docker compose."""

from __future__ import annotations

import os
import shutil
import subprocess
import time
from pathlib import Path

import httpx
import pytest

from kobo2ddi.ddi_xml import build_ddi_xml

COMPOSE_FILE = Path(__file__).parent / "docker-compose.validate.yml"
QWACBACK_TAG = os.environ.get("QWACBACK_TAG", "latest")
PB_PORT = os.environ.get("PB_PORT", "8090")
READY_TIMEOUT_S = float(os.environ.get("S2D_READY_TIMEOUT", "120"))

# Liveness probe: a minimal DDI document generated by the same builder both
# kobo2ddi and limesurvey2ddi use (limesurvey2ddi.transform.build_ddi_xml
# delegates to kobo2ddi.ddi_xml.build_ddi_xml). Used only to confirm the
# Java worker has replied at least once before tests run.
_PROBE_XML = build_ddi_xml(
    "Probe",
    [
        {"type": "text", "name": "probe_text", "label": "Probe text",
         "required": "false", "appearance": None},
        {"type": "integer", "name": "probe_num", "label": "Probe number",
         "required": "false", "appearance": None},
    ],
    {},
    {},
    [],
).encode("utf-8")


def _wait_for_ready(base_url: str, timeout_s: float) -> None:
    """Wait until PocketBase AND the Schematron worker are responsive.

    PocketBase readiness = GET /api returns 200. Worker readiness = a real
    /api/validate round-trip completes (200 valid or 400 invalid — either
    means the Java side replied; 5xx means the worker is unavailable).
    """
    deadline = time.monotonic() + timeout_s

    while time.monotonic() < deadline:
        try:
            r = httpx.get(f"{base_url}/api", timeout=2.0)
            if r.status_code == 200:
                break
        except httpx.HTTPError:
            pass
        time.sleep(1)
    else:
        pytest.fail(f"qwacback /api not ready within {timeout_s}s at {base_url}")

    while time.monotonic() < deadline:
        try:
            r = httpx.post(
                f"{base_url}/api/validate",
                files={"file": ("probe.xml", _PROBE_XML, "application/xml")},
                timeout=5.0,
            )
            if r.status_code in (200, 400):
                return
        except httpx.HTTPError:
            pass
        time.sleep(1)

    pytest.fail(f"schematron-worker not responsive within {timeout_s}s")


@pytest.fixture(scope="session")
def qwacback_base_url():
    if url := os.environ.get("S2D_VALIDATE_URL"):
        base = url.rstrip("/")
        _wait_for_ready(base, READY_TIMEOUT_S)
        yield base
        return

    if not shutil.which("docker"):
        pytest.skip("docker not available (set S2D_VALIDATE_URL to reuse a running stack)")

    project = f"s2d-validate-{os.getpid()}"
    env = {
        **os.environ,
        "QWACBACK_TAG": QWACBACK_TAG,
        "PB_PORT": PB_PORT,
    }

    subprocess.run(
        ["docker", "compose", "-p", project, "-f", str(COMPOSE_FILE),
         "up", "-d", "--wait", "--wait-timeout", str(int(READY_TIMEOUT_S))],
        check=True, env=env,
    )

    base = f"http://127.0.0.1:{PB_PORT}"
    try:
        _wait_for_ready(base, READY_TIMEOUT_S)
        yield base
    finally:
        subprocess.run(
            ["docker", "compose", "-p", project, "-f", str(COMPOSE_FILE),
             "down", "-v", "--remove-orphans"],
            check=False, env=env,
        )


@pytest.fixture
def validate_ddi(qwacback_base_url):
    """POST DDI XML to /api/validate; fail the test with error detail on rejection."""
    def _validate(xml: str | bytes, name: str = "test.xml") -> None:
        if isinstance(xml, str):
            xml = xml.encode("utf-8")
        r = _post_with_rate_limit_retry(
            f"{qwacback_base_url}/api/validate",
            files={"file": (name, xml, "application/xml")},
            timeout=30.0,
        )
        if r.status_code == 200:
            return

        try:
            body = r.json()
        except ValueError:
            pytest.fail(f"/api/validate -> HTTP {r.status_code}: {r.text[:500]}")

        errors = body.get("errors") or []
        if not errors:
            pytest.fail(f"/api/validate -> HTTP {r.status_code}: {body}")

        pretty = "\n".join(
            f"  - [{e.get('rule', '?')}] {e.get('message', '').strip()}"
            f" (at {e.get('location', '?')})"
            for e in errors
        )
        pytest.fail(
            f"qwacback rejected {name} ({len(errors)} error"
            f"{'s' if len(errors) != 1 else ''}):\n{pretty}"
        )

    return _validate


def _post_with_rate_limit_retry(
    url: str, *, max_total_wait_s: float = 90.0, **kwargs,
) -> httpx.Response:
    """POST with automatic backoff on HTTP 429.

    qwacback's guest rate limit is 10 POSTs/min. Integration suites easily
    exceed that; this helper sleeps on 429 (respecting Retry-After if sent,
    else a short fixed backoff) and retries until either success or the
    cumulative wait exceeds *max_total_wait_s*.
    """
    waited = 0.0
    while True:
        r = httpx.post(url, **kwargs)
        if r.status_code != 429:
            return r
        retry_after = float(r.headers.get("Retry-After") or 5.0)
        retry_after = min(retry_after, 10.0)
        if waited + retry_after > max_total_wait_s:
            return r
        time.sleep(retry_after)
        waited += retry_after


@pytest.fixture
def qwacback_convert_xlsform(qwacback_base_url):
    """POST an XLSForm (parsed-row shape) to /api/convert/xlsform-to-ddi.

    Accepts the same (survey_rows, choices_by_list, settings) triple that
    kobo2ddi.ddi_xml.build_ddi_xml consumes, transforms it into qwacback's
    XLSForm JSON shape, and returns the resulting DDI XML string.
    """
    def _convert(
        survey_rows: list[dict],
        choices_by_list: dict[str, list[dict]],
        settings: dict,
    ) -> str:
        mapped_settings = {}
        if "id_string" in settings:
            mapped_settings["form_id"] = settings["id_string"]
        if "form_title" in settings:
            mapped_settings["form_title"] = settings["form_title"]
        if "version" in settings:
            mapped_settings["version"] = settings["version"]

        payload = {
            "survey": survey_rows,
            "choices": [
                {"list_name": ln, "name": c["name"], "label": c["label"]}
                for ln, cs in choices_by_list.items()
                for c in cs
            ],
            "settings": mapped_settings,
        }
        r = _post_with_rate_limit_retry(
            f"{qwacback_base_url}/api/convert/xlsform-to-ddi",
            json=payload, timeout=30.0,
        )
        r.raise_for_status()
        return r.text

    return _convert
